buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
		maven {
			url = 'https://repo.grails.org/grails/restricted'
		}
	}
	dependencies {
		classpath platform("org.apache.grails:grails-bom:$grailsVersion")
		classpath "org.apache.grails:grails-gradle-plugins"
		classpath("com.gorylenko.gradle-git-properties:gradle-git-properties:4.0.1")
	}
}

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"org.apache.grails.gradle.grails-plugin"
apply plugin: "maven-publish"
apply plugin: "com.gorylenko.gradle-git-properties"

version = projectVersion
group = "org.grails.plugins"

apply plugin: 'org.apache.grails.gradle.grails-plugin'

ext {
	grailsVersion = project.grailsVersion
}

repositories {
	mavenLocal()
	mavenCentral()
	maven {
        url = "https://repo.grails.org/grails/core"
    }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-logging"
	implementation "org.springframework.boot:spring-boot-autoconfigure"
	implementation "org.apache.grails:grails-core"

	runtimeOnly "org.apache.grails:grails-web-boot"
	runtimeOnly "org.apache.grails:grails-dependencies-starter-web"
	runtimeOnly "javax.servlet:javax.servlet-api:${servletApiVersion}"

    console "org.apache.grails:grails-console"

    profile "org.apache.grails.profiles:plugin"

	implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
	implementation "org.apache.cxf:cxf-core:${cxfVersion}"
	implementation "org.apache.cxf:cxf-rt-frontend-jaxws:${cxfVersion}"
	implementation "org.apache.cxf:cxf-rt-frontend-jaxrs:${cxfVersion}"
	implementation "org.apache.cxf:cxf-rt-transports-http:${cxfVersion}"

	testImplementation "org.spockframework:spock-core"
}

compileJava.options.release = 17

// https://github.com/apache/grails-core/issues/15321
tasks.withType(GroovyCompile).configureEach {
	groovyOptions.optimizationOptions.indy = false
}

tasks.register('sourceJar', Jar) {
	dependsOn tasks.named('generateGitProperties')
	archiveClassifier = 'sources'
	from sourceSets.main.allSource
}

tasks.register('packageJavadoc', Jar) {
	archiveClassifier = 'javadoc'
	from javadoc
}

tasks.register('packageGroovydoc', Jar) {
	archiveClassifier = 'groovydoc'
	from groovydoc
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
}

gitProperties {
	keys = ['git.branch', 'git.commit.id', 'git.commit.time', 'git.commit.id.abbrev']
	failOnNoGitDirectory = true
	extProperty = 'gitProps' // git properties will be put in a map at project.ext.gitProps
}

generateGitProperties.outputs.upToDateWhen { false } // make sure the generateGitProperties task always executes (even when git.properties is not changed)

jar {
	dependsOn generateGitProperties
	manifest {
		attributes("Built-By": System.getProperty("user.name"))
		attributes(["Plugin-Version"        : version,
		            "Plugin-Title"          : project.name,
		            "Plugin-Build-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
		            "Git-Commit"            : "${-> project.ext.gitProps['git.commit.id.abbrev']}",
		            "Git-Branch"            : "${-> project.ext.gitProps['git.branch']}",
		            "Published-By"          : project.findProperty("nexusUsername") ?: System.getenv("NEXUS_USERNAME")])
	}
	from sourceSets.main.output
	exclude 'git.properties'
	exclude 'org/grails/cxf/test/**'
}

publishing {

	publications {
		library(MavenPublication) {
			from components.java
		}
		mavenJar(MavenPublication) {
			from components.java
			artifact sourceJar
			artifact packageJavadoc
			artifact packageGroovydoc
		}
	}

	repositories {
		maven {
			name = "GitHubPackages"
			url = uri("https://maven.pkg.github.com/vsachinv/grails-cxf")
			credentials {
				username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_USERNAME")
				password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
			}
		}
		maven {
			name = "NexusRepo"
			credentials {
				username project.findProperty("nexusUsername") ?: System.getenv("NEXUS_USERNAME")
				password project.findProperty("nexusPassword") ?: System.getenv("NEXUS_PASSWORD")
			}
			url project.findProperty("nexusUrl") ?: System.getenv("NEXUS_URL")
			allowInsecureProtocol = project.findProperty("isNexusUrlInsecure") ? true : false
		}
	}
}

// enable if you wish to package this plugin as a standalone application
bootJar.enabled = false

bootRun.onlyIf { false }
